# HW 2: Introduction and Setup
* Open the file "transforms.py"
* Complete the functions marked with "TODO"
* Run this notebook and check the output
* If your code is correct, the output should exactly match the rotation matrices shown below. 

In [1]:
# this cell will fail if you haven't correctly copied transforms.py 
# (and subsequent cells will fail if you haven't completed transforms.py)
import transforms as tr
import numpy as np


## 2D rotation by 20 degrees

A 2D rotation by 20 degrees should give the following:
$$
\left[\begin{array}{cc}
0.9397 & -0.342\\
0.342 & 0.9397
\end{array}\right]
$$

In [2]:
print("Define 2D Rotation with Angle = 20 degrees")
R = tr.rot2(20.0/180.0*np.pi)
print(R)

Define 2D Rotation with Angle = 20 degrees
[[ 0.93969262 -0.34202014]
 [ 0.34202014  0.93969262]]


## 2D rotation by 1.1 radians
A 2D rotation by 1.1 radians should give the following:
$$
\left[\begin{array}{cc}
0.4536 & -0.8912\\
0.8912 & 0.4536
\end{array}\right]
$$

In [3]:
print("\nSpecify that the angle is 1.1 radians")
R = tr.rot2(1.1)
print(R)


Specify that the angle is 1.1 radians
[[ 0.45359612 -0.89120736]
 [ 0.89120736  0.45359612]]


## 3D rotations $R_x(30)$, $R_y(25)$, and $R_z(15)$   (all in degrees) 

Using the "rotx" function to make a 3D rotation about the x axis of 30 degrees, we get:
$$
\left[\begin{array}{ccc}
1.0 & 0 & 0 \\
0 & 0.866 & -0.5 \\
0 & 0.5   & 0.866 
\end{array}\right]
$$

Using the "roty" function to make a 3D rotation about the y axis of 25 degrees, we get:
$$
\left[\begin{array}{ccc}
0.9063 & 0 & 0.4226 \\
0 & 1.0 & 0\\
-0.4226 & 0  & 0.9063 
\end{array}\right]
$$

Using the "rotz" function to make a 3D rotation about the z axis of 15 degrees, we get:
$$
\left[\begin{array}{ccc}
0.9659 & -0.2588 & 0 \\
0.2588 & 0.9659 & 0 \\
0 & 0 & 1.0
\end{array}\right]
$$

In [4]:
print("\nUse rotx to make a 3D rotation about the x axis of 30 degrees")
R = tr.rotx(30.0/180.0*np.pi)
print(R)

print("\nUse roty to make a 3D rotation about the y axis of 25 degrees")
R = tr.roty(25.0/180.0*np.pi)
print(R)

print("\nUse rotz to make a 3D rotation about the z axis of 15 degrees")
R = tr.rotz(15.0/180.0*np.pi)
print(R)


Use rotx to make a 3D rotation about the x axis of 30 degrees
[[ 1.         0.         0.       ]
 [ 0.         0.8660254 -0.5      ]
 [ 0.         0.5        0.8660254]]

Use roty to make a 3D rotation about the y axis of 25 degrees
[[ 0.90630779  0.          0.42261826]
 [ 0.          1.          0.        ]
 [-0.42261826  0.          0.90630779]]

Use rotz to make a 3D rotation about the z axis of 15 degrees
[[ 0.96592583 -0.25881905  0.        ]
 [ 0.25881905  0.96592583  0.        ]
 [ 0.          0.          1.        ]]


## Composition of 3D rotations:

Composing a 3D rotation about the x, y, and z axes as follows $R_x(10)*R_y(15)*R_z(20)$ (all in degrees), should give: 
$$
\left[\begin{array}{ccc}
0.9077 & -0.3304 & 0.2588 \\
0.3791 & 0.91 & -0.1677 \\
-0.1801 & 0.2504 & 0.9512 
\end{array}\right]
$$

Finding the inverse of a rotation matrix, and multiplying it by the original rotation matrix, should result in the identity matrix:
$$
\left[\begin{array}{ccc}
1.0 & 0 & 0 \\
0 & 1.0 & 0 \\
0 & 0 & 1.0
\end{array}\right]
$$

In [5]:
print("\nCompose multiple rotations about the x, y, and z axes")
R = tr.rotx(10/180.0*np.pi) @ tr.roty(15/180.0*np.pi) @ tr.rotz(20/180.0*np.pi)
print(R)

print("\nDemonstrate that your implementation of the .inv() function returns the inverse of a rotation")
R = tr.rotx(20/180.0*np.pi)
R = R @ tr.rot_inv(R)
print(R)
print("\n")


Compose multiple rotations about the x, y, and z axes
[[ 0.90767337 -0.33036609  0.25881905]
 [ 0.37905712  0.91004501 -0.16773126]
 [-0.18012426  0.2503524   0.95125124]]

Demonstrate that your implementation of the .inv() function returns the inverse of a rotation
[[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 2.22218033e-17]
 [0.00000000e+00 2.22218033e-17 1.00000000e+00]]




## Checking commutativity:

The previoius rotation described as $R_x(10)*R_y(15)*R_z(20)$ (all in degrees), gave the following: 
$$
\left[\begin{array}{ccc}
0.9077 & -0.3304 & 0.2588 \\
0.3791 & 0.91 & -0.1677 \\
-0.1801 & 0.2504 & 0.9512 
\end{array}\right]
$$

Show that performing the operations in the opposite order does NOT give the same result. 

In [6]:
print("\nRotation about current z, then y, then x axes:")
R = tr.rotz(20/180.0*np.pi) @ tr.roty(15/180.0*np.pi) @ tr.rotx(10/180.0*np.pi)
print(R)


Rotation about current z, then y, then x axes:
[[ 0.90767337 -0.29459106  0.29890661]
 [ 0.33036609  0.94078815 -0.07599942]
 [-0.25881905  0.16773126  0.95125124]]


## Animating a Coordinate Frame

We can implement and test the code for problem 9 here:

In [ ]:
import time
from visualization import VizScene 

viz = VizScene()
viz.add_frame(np.eye(4), label='world', axes_label='w')
viz.add_frame(np.eye(4), label='frame1', axes_label='f1')

time_to_run = 10 # seconds
refresh_rate = 60 # Hz
t = 0
start = time.time()

while t < time_to_run:
    t = time.time() - start

    Tw_to_frame1 = np.eye(4)

    # you can play with omega and p to see how they affect the frame
    omega = np.pi/2
    R = tr.roty(10/180.0*np.pi * t)

    p = np.array([1, 0, 0])

    Tw_to_frame1[:3,:3] = R
    Tw_to_frame1[:3, 3] = p

    viz.update(As=[np.eye(4), Tw_to_frame1])

viz.hold()

# now you can use functions like "VizScene" and "add_frame" 
# as demonstrated in HW 01 to animate a frame.  
