# HW 2: Introduction and Setup
* Open the file "transforms.py"
* Complete the functions marked with "TODO"
* Run this notebook and check the output
* If your code is correct, the output should exactly match the rotation matrices shown below. 

In [25]:
# this cell will fail if you haven't correctly copied transforms.py 
# (and subsequent cells will fail if you haven't completed transforms.py)
import transforms as tr
import numpy as np


## 2D rotation by 20 degrees

A 2D rotation by 20 degrees should give the following:
$$
\left[\begin{array}{cc}
0.9397 & -0.342\\
0.342 & 0.9397
\end{array}\right]
$$

In [26]:
print("Define 2D Rotation with Angle = 20 degrees")
R = tr.rot2(20.0/180.0*np.pi)
R_round = np.round(R, 4)
print(R_round)

Define 2D Rotation with Angle = 20 degrees
[[ 0.9397 -0.342 ]
 [ 0.342   0.9397]]


## 2D rotation by 1.1 radians
A 2D rotation by 1.1 radians should give the following:
$$
\left[\begin{array}{cc}
0.4536 & -0.8912\\
0.8912 & 0.4536
\end{array}\right]
$$

In [27]:
print("\nSpecify that the angle is 1.1 radians")
R = tr.rot2(1.1)
R_round = np.round(R, 4)
print(R_round)
#print(R)


Specify that the angle is 1.1 radians
[[ 0.4536 -0.8912]
 [ 0.8912  0.4536]]


## 3D rotations $R_x(30)$, $R_y(25)$, and $R_z(15)$   (all in degrees) 

Using the "rotx" function to make a 3D rotation about the x axis of 30 degrees, we get:
$$
\left[\begin{array}{ccc}
1.0 & 0 & 0 \\
0 & 0.866 & -0.5 \\
0 & 0.5   & 0.866 
\end{array}\right]
$$

Using the "roty" function to make a 3D rotation about the y axis of 25 degrees, we get:
$$
\left[\begin{array}{ccc}
0.9063 & 0 & 0.4226 \\
0 & 1.0 & 0\\
-0.4226 & 0  & 0.9063 
\end{array}\right]
$$

Using the "rotz" function to make a 3D rotation about the z axis of 15 degrees, we get:
$$
\left[\begin{array}{ccc}
0.9659 & -0.2588 & 0 \\
0.2588 & 0.9659 & 0 \\
0 & 0 & 1.0
\end{array}\right]
$$

In [28]:
print("\nUse rotx to make a 3D rotation about the x axis of 30 degrees")
R = tr.rotx(30.0/180.0*np.pi)
#print(R)
R_round = np.round(R, 3)
print(R_round)

print("\nUse roty to make a 3D rotation about the y axis of 25 degrees")
R = tr.roty(25.0/180.0*np.pi)
#print(R)
R_round = np.round(R, 4)
print(R_round)


print("\nUse rotz to make a 3D rotation about the z axis of 15 degrees")
R = tr.rotz(15.0/180.0*np.pi)
#print(R)
R_round = np.round(R, 4)
print(R_round)


Use rotx to make a 3D rotation about the x axis of 30 degrees
[[ 1.     0.     0.   ]
 [ 0.     0.866 -0.5  ]
 [ 0.     0.5    0.866]]

Use roty to make a 3D rotation about the y axis of 25 degrees
[[ 0.9063  0.      0.4226]
 [ 0.      1.      0.    ]
 [-0.4226  0.      0.9063]]

Use rotz to make a 3D rotation about the z axis of 15 degrees
[[ 0.9659 -0.2588  0.    ]
 [ 0.2588  0.9659  0.    ]
 [ 0.      0.      1.    ]]


## Composition of 3D rotations:

Composing a 3D rotation about the x, y, and z axes as follows $R_x(10)*R_y(15)*R_z(20)$ (all in degrees), should give: 
$$
\left[\begin{array}{ccc}
0.9077 & -0.3304 & 0.2588 \\
0.3791 & 0.91 & -0.1677 \\
-0.1801 & 0.2504 & 0.9512 
\end{array}\right]
$$

Finding the inverse of a rotation matrix, and multiplying it by the original rotation matrix, should result in the identity matrix:
$$
\left[\begin{array}{ccc}
1.0 & 0 & 0 \\
0 & 1.0 & 0 \\
0 & 0 & 1.0
\end{array}\right]
$$

In [29]:
print("\nCompose multiple rotations about the x, y, and z axes")
R = tr.rotx(10/180.0*np.pi) @ tr.roty(15/180.0*np.pi) @ tr.rotz(20/180.0*np.pi)
R_round = np.round(R, 4)
print(R_round)

print("\nDemonstrate that your implementation of the .inv() function returns the inverse of a rotation")
R = tr.rotx(20/180.0*np.pi)
R = R @ tr.rot_inv(R)
R_round = np.round(R, 1)
print(R_round)
print("\n")


Compose multiple rotations about the x, y, and z axes
[[ 0.9077 -0.3304  0.2588]
 [ 0.3791  0.91   -0.1677]
 [-0.1801  0.2504  0.9513]]

Demonstrate that your implementation of the .inv() function returns the inverse of a rotation
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]




## Checking commutativity:

The previoius rotation described as $R_x(10)*R_y(15)*R_z(20)$ (all in degrees), gave the following: 
$$
\left[\begin{array}{ccc}
0.9077 & -0.3304 & 0.2588 \\
0.3791 & 0.91 & -0.1677 \\
-0.1801 & 0.2504 & 0.9512 
\end{array}\right]
$$

Show that performing the operations in the opposite order does NOT give the same result. 

In [30]:
print("\nRotation about current z, then y, then x axes:")
R = tr.rotz(20/180.0*np.pi) @ tr.roty(15/180.0*np.pi) @ tr.rotx(10/180.0*np.pi)
R_round = np.round(R, 4)
print(R_round)


Rotation about current z, then y, then x axes:
[[ 0.9077 -0.2946  0.2989]
 [ 0.3304  0.9408 -0.076 ]
 [-0.2588  0.1677  0.9513]]


## Animating a Coordinate Frame

We can implement and test the code for problem 9 here:

In [31]:
import time
from visualization import VizScene 

viz = VizScene()
viz.add_frame(np.eye(4), label='world', axes_label='w')
viz.add_frame(np.eye(4), label='frame1', axes_label='f1')

time_to_run = 10 # seconds
refresh_rate = 60 # Hz
t = 0
start = time.time()

while t < time_to_run:
    t = time.time() - start

    Tw_to_frame1 = np.eye(4)

    # you can play with omega and p to see how they affect the frame
    omega = np.pi/2
    R = tr.roty(10/180.0*np.pi * t)

    p = np.array([1, 0, 0])

    Tw_to_frame1[:3,:3] = R
    Tw_to_frame1[:3, 3] = p

    viz.update(As=[np.eye(4), Tw_to_frame1])

viz.hold()

# now you can use functions like "VizScene" and "add_frame" 
# as demonstrated in HW 01 to animate a frame.  


Error while drawing item <pyqtgraph.opengl.items.GLMeshItem.GLMeshItem object at 0x0000022ADAD725F0>.


c:\Users\maxgunn\Desktop\2025 Fall Classes\Robotics\CodeBase\.venv\Lib\site-packages\pyqtgraph\opengl\GLViewWidget.py:231: RuntimeWarning: 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\maxgunn\Desktop\2025 Fall Classes\Robotics\CodeBase\.venv\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\Users\maxgunn\Desktop\2025 Fall Classes\Robotics\CodeBase\.venv\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\maxgunn\Desktop\2025 Fall Classes\Robotics\CodeBase\.venv\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "c:\Users\maxgunn\Desktop\2025 Fall Classes\Robotics\CodeBase\.venv\Lib\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "C:\Program Files\WindowsApps\Py

GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glMatrixMode,
	cArguments = (GL_MODELVIEW,)
)

**Problem 2**  
For the rest of the problems in this homework, you may either continue using the notebook, make your own Python script, or do some problems by hand (whichever you prefer).  

I strongly recommend using **SymPy** as it will come in handy for future homework. To better understand the capabilities of symbolic manipulation with the SymPy library, please run the **`sympy_tutorial.ipynb`** file from the class homework repository.  

You may find it especially useful to define symbolic variables (such as **θ, φ, ψ**) for some problems. Mixing data types like **`numpy.array`** objects (used in **`transforms.py`**) and **SymPy `Matrix`** objects (demonstrated in **`sympy_tutorial.ipynb`**) does not work well. However, in some cases, using symbolic variables is still useful and worthwhile.  

This problem is **graded by completion** if you step through each part of the SymPy introduction.

In [32]:
print("Done")

Done


**Problem 3**  
Consider the following sequences of rotations and write the matrix product that will give the resulting rotation matrix (don't perform the operation, just write the correct order -e.g. $R_x(\alpha)R_y(\beta)$ etc.):  
  
(a) rotate by $\phi$ in the **x-axis**, $\theta$ in the **z-axis**, then $\psi$ in the **y-axis** all in the current frame.  
(b) rotate by $\phi$ in the **x-axis**, $\theta$ in the **z-axis**, then $\psi$ in the **y-axis** all in the fixed world frame.


**Answer**  
$$(a)\quad R = R_{x}(\phi) \, R_{z}(\theta) \, R_{y}(\psi) \\
(b)\quad R = R_{y}(\psi) \, R_{z}(\theta) \, R_{x}(\phi)$$


**Problem 4**  
A camera has its **z-axis** parallel to the vector **[0, 1, 0]** in the world frame, and its **y-axis** parallel to the vector **[0, 0, −1]**.  

What is the **attitude of the camera** with respect to the world frame expressed as a **rotation matrix**?


In [33]:
import numpy as np

# Define the camera's axes in world frame coordinates
z_c = np.array([0, 1, 0])

# The camera's y-axis is parallel to the world's negative z-axis [0, 0, -1]
y_c = np.array([0, 0, -1])

# For a right-handed coordinate system, the x-axis is found by the cross product: x = y x z
x_c = np.cross(y_c, z_c)

R_w_c = np.column_stack((x_c, y_c, z_c))

print("Attitude of the camera (R^w_c):\n", R_w_c)

Attitude of the camera (R^w_c):
 [[ 1  0  0]
 [ 0  0  1]
 [ 0 -1  0]]


**Problem 5**  
If coordinate frame **o₁** is obtained by rotating coordinate frame **o₀** by **π/2** about the **x-axis**, followed by a rotation of **π/2** about the **y-axis**, find the **rotation matrix R** that represents the composite transformation.  

Sketch the initial and final frames (or use the **`addframe`** function again).  
This is for **rotations about a fixed axis**.


In [34]:
import numpy as np

# Define 3D rotation matrix functions (from Problem 1)
def rotx(theta):
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[1, 0, 0], [0, c, -s], [0, s, c]])

def roty(theta):
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[c, 0, s], [0, 1, 0], [-s, 0, c]])

# Define the rotation angles
theta_x = np.pi / 2
theta_y = np.pi / 2

# Calculate the individual rotation matrices
R_x = rotx(theta_x)
R_y = roty(theta_y)

# For rotations about a fixed world axis, the composite transformation
# is found by pre-multiplying. The rotation about x occurs first,
# so the multiplication order is R_y * R_x.
R_composite = R_y @ R_x

# Use np.round to clean up floating point inaccuracies for display
print("Composite rotation matrix R = R_y(pi/2) * R_x(pi/2):\n", np.round(R_composite, decimals=5))

Composite rotation matrix R = R_y(pi/2) * R_x(pi/2):
 [[ 0.  1.  0.]
 [ 0.  0. -1.]
 [-1.  0.  0.]]


**Problem 6**  
Suppose three coordinate frames (**o₁, o₂, o₃**) are given, and that:

\[
R^1_2 =
\begin{bmatrix}
1 & 0 & 0 \\
0 & \tfrac{1}{2} & -\tfrac{\sqrt{3}}{2} \\
0 & \tfrac{\sqrt{3}}{2} & \tfrac{1}{2}
\end{bmatrix}, \quad
R^1_3 =
\begin{bmatrix}
0 & 0 & -1 \\
0 & 1 & 0 \\
1 & 0 & 0
\end{bmatrix}
\]

Find the matrix **R²₃**.


In [35]:
import numpy as np

# Given rotation matrices
R1_2 = np.array([[1, 0,           0          ],
                 [0, 1/2,        -np.sqrt(3)/2],
                 [0, np.sqrt(3)/2, 1/2        ]])

R1_3 = np.array([[0, 0, -1],
                 [0, 1,  0],
                 [1, 0,  0]])

# We have the relationship: R^1_3 = R^1_2 * R^2_3

# The inverse of a rotation matrix is its transpose
R2_1 = R1_2.T  # This is equivalent to (R^1_2)^-1

# Calculate R^2_3 by matrix multiplication
R2_3 = R2_1 @ R1_3

print("The matrix R^2_3 is:\n", R2_3)

The matrix R^2_3 is:
 [[ 0.         0.        -1.       ]
 [ 0.8660254  0.5        0.       ]
 [ 0.5       -0.8660254  0.       ]]


**Problem 7**  
Compute the rotation matrix given by the following product (you may use symbolic variables to do this, and remember that **φ** and **θ** are variables, but **π** is a numerical value that should be evaluated):

$$R_{x, \theta} \, R_{y, \phi} \, R_{z, \pi} \, R_{y, -\phi} \, R_{x, -\theta}$$


In [46]:
import sympy as sp

# Define symbolic variables
theta, phi = sp.symbols('theta phi', real=True)

# Define rotation matrices
def R_x(a):
    return sp.Matrix([
        [1, 0, 0],
        [0, sp.cos(a), -sp.sin(a)],
        [0, sp.sin(a), sp.cos(a)]
    ])

def R_y(a):
    return sp.Matrix([
        [sp.cos(a), 0, sp.sin(a)],
        [0, 1, 0],
        [-sp.sin(a), 0, sp.cos(a)]
    ])

def R_z(a):
    return sp.Matrix([
        [sp.cos(a), -sp.sin(a), 0],
        [sp.sin(a), sp.cos(a), 0],
        [0, 0, 1]
    ])

# Build the product
R = R_x(theta) * R_y(phi) * R_z(sp.pi) * R_y(-phi) * R_x(-theta)

# Force it into basic sin/cos form
R_clean = sp.expand_trig(R)   # expand cos(2φ), sin(2φ), etc.
R_clean = sp.factor(R_clean)  # optional: factor neatness

print("Rotation matrix:")
sp.pprint(R_clean, use_unicode=True)


Rotation matrix:
⎡      2         2                                                             ↪
⎢   sin (φ) - cos (φ)                       -2⋅sin(φ)⋅sin(θ)⋅cos(φ)            ↪
⎢                                                                              ↪
⎢                               ⎛   2                       2   ⎞              ↪
⎢-2⋅sin(φ)⋅sin(θ)⋅cos(φ)      - ⎝sin (φ)⋅sin(θ) - sin(θ)⋅cos (φ)⎠⋅sin(θ) - cos ↪
⎢                                                                              ↪
⎢                           ⎛     2                2          ⎞                ↪
⎣2⋅sin(φ)⋅cos(φ)⋅cos(θ)   - ⎝- sin (φ)⋅cos(θ) + cos (φ)⋅cos(θ)⎠⋅sin(θ) - sin(θ ↪

↪                                                                   ⎤
↪                            2⋅sin(φ)⋅cos(φ)⋅cos(θ)                 ⎥
↪                                                                   ⎥
↪ 2         ⎛   2                       2   ⎞                       ⎥
↪  (θ)      ⎝sin (φ)⋅sin(θ) - sin(θ)⋅cos (φ)⎠⋅cos(θ) -

**Problem 8**  
Find the rotation matrix corresponding to the Euler angles **φ = π/2**, **θ = 0**, and **ψ = π/4**, about the **Z, then Y, then Z axes**.  

What is the **direction of the new x-axis** relative to the base frame?


In [38]:
import numpy as np

# Define the 3D rotation matrix function for the z-axis
def rotz(theta):
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[c, -s, 0], [s, c, 0], [0, 0, 1]])

# Define the 3D rotation matrix function for the y-axis
def roty(theta):
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[c, 0, s], [0, 1, 0], [-s, 0, c]])

# Given Euler angles for the Z-Y-Z convention:
phi = np.pi / 2  # First rotation about Z
theta = 0        # Second rotation about new Y
psi = np.pi / 4  # Third rotation about new Z

# matrix is R = R_z(phi) * R_y(theta) * R_z(psi).
Rz_phi = rotz(phi)
Ry_theta = roty(theta)
Rz_psi = rotz(psi)

R_total = Rz_phi @ Ry_theta @ Rz_psi

# the first column of the final rotation matrix.
new_x_axis = R_total[:, 0]

#print("Rotation matrix for Z(pi/2) Y(0) Z(pi/4) Euler angles:\n", np.round(R_total, decimals=5))
print("\nDirection of the new x-axis:\n", np.round(new_x_axis, decimals=5))


Direction of the new x-axis:
 [-0.70711  0.70711  0.     ]


**Problem 9**  
Make an **animation of a rotating coordinate frame** and either video it with a phone or screen capture for submission.  

You can do this in a new Python file, or use the Jupyter notebook (building on examples from HW01). You can describe this transform using an equation like the following (but you can also pick your own as long as it results in an actual rotation matrix in the top-left 3×3 entries):

\[
T^w_1(t) =
\begin{bmatrix}
\cos\left(\tfrac{\pi}{2} t\right) & -\sin\left(\tfrac{\pi}{2} t\right) & 0 & 1 \\
\sin\left(\tfrac{\pi}{2} t\right) & \cos\left(\tfrac{\pi}{2} t\right) & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
\]

The animation can be done using the **`addframe`** function from HW01, but by passing an additional argument to the **`viz.update()`** function as follows (where the matrix argument just tells our function how to change the frame orientation over time):

```python
viz.update(As=[np.eye(4), Tw_to_frame1])


In [55]:
import numpy as np
import time
from visualization import VizScene

# --- Setup the visualization ---
Tw_to_frame1 = np.eye(4)
viz = VizScene()
viz.add_frame(np.eye(4), label='world', axes_label='w')
viz.add_frame(Tw_to_frame1, label='frame1', axes_label='1')

# --- Animation Loop ---
time_to_run = 10
refresh_rate = 60 # The target frames per second
t = 0
start = time.time()

while t < time_to_run:
    # Get the current elapsed time
    t = time.time() - start
    
    # Define the angular velocity
    omega = np.pi / 2
    
    # 1. Create the 3x3 rotation matrix as a function of time
    R_3x3 = np.array([
        [np.cos(omega * t), -np.sin(omega * t), 0],
        [np.sin(omega * t),  np.cos(omega * t), 0],
        [0,                  0,                 1]
    ])
    
    # 2. Create the 3x1 position vector as a function of time for smooth motion
    p_3x1 = np.array([1, 0, 0])
    
    # 3. Assemble the final 4x4 homogeneous transformation matrix
    Tw_to_frame1 = np.eye(4)      # Start with a clean identity matrix
    Tw_to_frame1[:3, :3] = R_3x3  # Set the rotation part
    Tw_to_frame1[:3, 3] = p_3x1   # Set the translation part
    
    # 4. Update the visualization with the new matrix
    viz.update(As=[np.eye(4), Tw_to_frame1])
    
    # 5. Wait for a short period to maintain the desired refresh rate
    time.sleep(1 / refresh_rate)

viz.close_viz()

Error while drawing item <pyqtgraph.opengl.items.GLMeshItem.GLMeshItem object at 0x0000022AD88436D0>.


c:\Users\maxgunn\Desktop\2025 Fall Classes\Robotics\CodeBase\.venv\Lib\site-packages\pyqtgraph\opengl\GLViewWidget.py:231: RuntimeWarning: 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\maxgunn\Desktop\2025 Fall Classes\Robotics\CodeBase\.venv\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\Users\maxgunn\Desktop\2025 Fall Classes\Robotics\CodeBase\.venv\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\maxgunn\Desktop\2025 Fall Classes\Robotics\CodeBase\.venv\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "c:\Users\maxgunn\Desktop\2025 Fall Classes\Robotics\CodeBase\.venv\Lib\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "C:\Program Files\WindowsApps\Py

GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glMatrixMode,
	cArguments = (GL_MODELVIEW,)
)