# HW 2: Introduction and Setup
* Open the file "transforms.py"
* Complete the functions marked with "TODO"
* Run this notebook and check the output
* If your code is correct, the output should exactly match the rotation matrices shown below. 

In [2]:
# this cell will fail if you haven't correctly copied transforms.py 
# (and subsequent cells will fail if you haven't completed transforms.py)
import transforms as tr
import numpy as np


## 2D rotation by 20 degrees

A 2D rotation by 20 degrees should give the following:
$$
\left[\begin{array}{cc}
0.9397 & -0.342\\
0.342 & 0.9397
\end{array}\right]
$$

In [14]:
print("Define 2D Rotation with Angle = 20 degrees")
R = tr.rot2(20.0/180.0*np.pi)
R_round = np.round(R, 4)
print(R_round)

Define 2D Rotation with Angle = 20 degrees
[[ 0.9397 -0.342 ]
 [ 0.342   0.9397]]


## 2D rotation by 1.1 radians
A 2D rotation by 1.1 radians should give the following:
$$
\left[\begin{array}{cc}
0.4536 & -0.8912\\
0.8912 & 0.4536
\end{array}\right]
$$

In [15]:
print("\nSpecify that the angle is 1.1 radians")
R = tr.rot2(1.1)
R_round = np.round(R, 4)
print(R_round)
#print(R)


Specify that the angle is 1.1 radians
[[ 0.4536 -0.8912]
 [ 0.8912  0.4536]]


## 3D rotations $R_x(30)$, $R_y(25)$, and $R_z(15)$   (all in degrees) 

Using the "rotx" function to make a 3D rotation about the x axis of 30 degrees, we get:
$$
\left[\begin{array}{ccc}
1.0 & 0 & 0 \\
0 & 0.866 & -0.5 \\
0 & 0.5   & 0.866 
\end{array}\right]
$$

Using the "roty" function to make a 3D rotation about the y axis of 25 degrees, we get:
$$
\left[\begin{array}{ccc}
0.9063 & 0 & 0.4226 \\
0 & 1.0 & 0\\
-0.4226 & 0  & 0.9063 
\end{array}\right]
$$

Using the "rotz" function to make a 3D rotation about the z axis of 15 degrees, we get:
$$
\left[\begin{array}{ccc}
0.9659 & -0.2588 & 0 \\
0.2588 & 0.9659 & 0 \\
0 & 0 & 1.0
\end{array}\right]
$$

In [9]:
print("\nUse rotx to make a 3D rotation about the x axis of 30 degrees")
R = tr.rotx(30.0/180.0*np.pi)
#print(R)
R_round = np.round(R, 3)
print(R_round)

print("\nUse roty to make a 3D rotation about the y axis of 25 degrees")
R = tr.roty(25.0/180.0*np.pi)
#print(R)
R_round = np.round(R, 4)
print(R_round)


print("\nUse rotz to make a 3D rotation about the z axis of 15 degrees")
R = tr.rotz(15.0/180.0*np.pi)
#print(R)
R_round = np.round(R, 4)
print(R_round)


Use rotx to make a 3D rotation about the x axis of 30 degrees
[[ 1.     0.     0.   ]
 [ 0.     0.866 -0.5  ]
 [ 0.     0.5    0.866]]

Use roty to make a 3D rotation about the y axis of 25 degrees
[[ 0.9063  0.      0.4226]
 [ 0.      1.      0.    ]
 [-0.4226  0.      0.9063]]

Use rotz to make a 3D rotation about the z axis of 15 degrees
[[ 0.9659 -0.2588  0.    ]
 [ 0.2588  0.9659  0.    ]
 [ 0.      0.      1.    ]]


## Composition of 3D rotations:

Composing a 3D rotation about the x, y, and z axes as follows $R_x(10)*R_y(15)*R_z(20)$ (all in degrees), should give: 
$$
\left[\begin{array}{ccc}
0.9077 & -0.3304 & 0.2588 \\
0.3791 & 0.91 & -0.1677 \\
-0.1801 & 0.2504 & 0.9512 
\end{array}\right]
$$

Finding the inverse of a rotation matrix, and multiplying it by the original rotation matrix, should result in the identity matrix:
$$
\left[\begin{array}{ccc}
1.0 & 0 & 0 \\
0 & 1.0 & 0 \\
0 & 0 & 1.0
\end{array}\right]
$$

In [12]:
print("\nCompose multiple rotations about the x, y, and z axes")
R = tr.rotx(10/180.0*np.pi) @ tr.roty(15/180.0*np.pi) @ tr.rotz(20/180.0*np.pi)
R_round = np.round(R, 4)
print(R_round)

print("\nDemonstrate that your implementation of the .inv() function returns the inverse of a rotation")
R = tr.rotx(20/180.0*np.pi)
R = R @ tr.rot_inv(R)
R_round = np.round(R, 1)
print(R_round)
print("\n")


Compose multiple rotations about the x, y, and z axes
[[ 0.9077 -0.3304  0.2588]
 [ 0.3791  0.91   -0.1677]
 [-0.1801  0.2504  0.9513]]

Demonstrate that your implementation of the .inv() function returns the inverse of a rotation
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]




## Checking commutativity:

The previoius rotation described as $R_x(10)*R_y(15)*R_z(20)$ (all in degrees), gave the following: 
$$
\left[\begin{array}{ccc}
0.9077 & -0.3304 & 0.2588 \\
0.3791 & 0.91 & -0.1677 \\
-0.1801 & 0.2504 & 0.9512 
\end{array}\right]
$$

Show that performing the operations in the opposite order does NOT give the same result. 

In [13]:
print("\nRotation about current z, then y, then x axes:")
R = tr.rotz(20/180.0*np.pi) @ tr.roty(15/180.0*np.pi) @ tr.rotx(10/180.0*np.pi)
R_round = np.round(R, 4)
print(R_round)


Rotation about current z, then y, then x axes:
[[ 0.9077 -0.2946  0.2989]
 [ 0.3304  0.9408 -0.076 ]
 [-0.2588  0.1677  0.9513]]


## Animating a Coordinate Frame

We can implement and test the code for problem 9 here:

In [22]:
import time
from visualization import VizScene 

viz = VizScene()
viz.add_frame(np.eye(4), label='world', axes_label='w')
viz.add_frame(np.eye(4), label='frame1', axes_label='f1')

time_to_run = 10 # seconds
refresh_rate = 60 # Hz
t = 0
start = time.time()

while t < time_to_run:
    t = time.time() - start

    Tw_to_frame1 = np.eye(4)

    # you can play with omega and p to see how they affect the frame
    omega = np.pi/2
    R = tr.roty(10/180.0*np.pi * t)

    p = np.array([1, 0, 0])

    Tw_to_frame1[:3,:3] = R
    Tw_to_frame1[:3, 3] = p

    viz.update(As=[np.eye(4), Tw_to_frame1])

viz.hold()

# now you can use functions like "VizScene" and "add_frame" 
# as demonstrated in HW 01 to animate a frame.  


**Problem 2**  
For the rest of the problems in this homework, you may either continue using the notebook, make your own Python script, or do some problems by hand (whichever you prefer).  

I strongly recommend using **SymPy** as it will come in handy for future homework. To better understand the capabilities of symbolic manipulation with the SymPy library, please run the **`sympy_tutorial.ipynb`** file from the class homework repository.  

You may find it especially useful to define symbolic variables (such as **θ, φ, ψ**) for some problems. Mixing data types like **`numpy.array`** objects (used in **`transforms.py`**) and **SymPy `Matrix`** objects (demonstrated in **`sympy_tutorial.ipynb`**) does not work well. However, in some cases, using symbolic variables is still useful and worthwhile.  

This problem is **graded by completion** if you step through each part of the SymPy introduction.

In [23]:
print("Done")

Done


**Problem 3**  
Consider the following sequences of rotations and write the matrix product that will give the resulting rotation matrix (don't perform the operation, just write the correct order -e.g. $R_x(\alpha)R_y(\beta)$ etc.):  
  
(a) rotate by $\phi$ in the **x-axis**, $\theta$ in the **z-axis**, then $\psi$ in the **y-axis** all in the current frame.  
(b) rotate by $\phi$ in the **x-axis**, $\theta$ in the **z-axis**, then $\psi$ in the **y-axis** all in the fixed world frame.


**Problem 4**  
A camera has its **z-axis** parallel to the vector **[0, 1, 0]** in the world frame, and its **y-axis** parallel to the vector **[0, 0, −1]**.  

What is the **attitude of the camera** with respect to the world frame expressed as a **rotation matrix**?


**Problem 5**  
If coordinate frame **o₁** is obtained by rotating coordinate frame **o₀** by **π/2** about the **x-axis**, followed by a rotation of **π/2** about the **y-axis**, find the **rotation matrix R** that represents the composite transformation.  

Sketch the initial and final frames (or use the **`addframe`** function again).  
This is for **rotations about a fixed axis**.


**Problem 6**  
Suppose three coordinate frames (**o₁, o₂, o₃**) are given, and that:

\[
R^1_2 =
\begin{bmatrix}
1 & 0 & 0 \\
0 & \tfrac{1}{2} & -\tfrac{\sqrt{3}}{2} \\
0 & \tfrac{\sqrt{3}}{2} & \tfrac{1}{2}
\end{bmatrix}, \quad
R^1_3 =
\begin{bmatrix}
0 & 0 & -1 \\
0 & 1 & 0 \\
1 & 0 & 0
\end{bmatrix}
\]

Find the matrix **R²₃**.


**Problem 7**  
Compute the rotation matrix given by the following product (you may use symbolic variables to do this, and remember that **φ** and **θ** are variables, but **π** is a numerical value that should be evaluated):

$$R_{x, \theta} \, R_{y, \phi} \, R_{z, \pi} \, R_{y, -\phi} \, R_{x, -\theta}$$


**Problem 8**  
Find the rotation matrix corresponding to the Euler angles **φ = π/2**, **θ = 0**, and **ψ = π/4**, about the **Z, then Y, then Z axes**.  

What is the **direction of the new x-axis** relative to the base frame?


**Problem 9**  
Make an **animation of a rotating coordinate frame** and either video it with a phone or screen capture for submission.  

You can do this in a new Python file, or use the Jupyter notebook (building on examples from HW01). You can describe this transform using an equation like the following (but you can also pick your own as long as it results in an actual rotation matrix in the top-left 3×3 entries):

\[
T^w_1(t) =
\begin{bmatrix}
\cos\left(\tfrac{\pi}{2} t\right) & -\sin\left(\tfrac{\pi}{2} t\right) & 0 & 1 \\
\sin\left(\tfrac{\pi}{2} t\right) & \cos\left(\tfrac{\pi}{2} t\right) & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
\]

The animation can be done using the **`addframe`** function from HW01, but by passing an additional argument to the **`viz.update()`** function as follows (where the matrix argument just tells our function how to change the frame orientation over time):

```python
viz.update(As=[np.eye(4), Tw_to_frame1])
